import Navbar from "@/components/Navbar";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'

export const metadata = {
  title: "Job list application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <AuthProvider>
    <html>
        <body>
          <Navbar/>
          <main>{children}</main>
          <ToastContainer />
        </body>
    </html>
      </AuthProvider>
  );
}
