import Navbar from "@/components/Navbar";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "Job list application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <AuthProvider>
    <html>
        <body>
          <Navbar/>
          <main>{children}</main>
        </body>
    </html>
      </AuthProvider>
  );
}
